#!/bin/sh

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

bad_usage()
{
    printf 'Usage: %s -i IN-DIR -o SYNC-DIR IDENT...\n' "${0##*/}" >&2
    exit 1
}

indir=
syncdir=
while getopts 'i:o:' opt
do
    case "$opt" in
        i) indir="$OPTARG";;
        o) syncdir="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND-1))
[ $# -ne 0 ] || bad_usage
[ -n "$indir" ] || bad_usage
[ -n "$syncdir" ] || bad_usage

mkdir -p "$syncdir"
for node in "$@"
do
    mkdir "$syncdir/$node"
    queue="$syncdir/$node/queue"
    mkdir "$queue"
    i=0
    for file in "$indir/"*
    do
        tmpfile=$(mktemp -p "$queue" .tmpinject.XXXXX)
        basename="${file##*/}"
        name=$(printf 'id:%06d,orig:%s' "$i" "$basename")
        printf '%s -> %s\n' "$file" "$queue/$name"
        cat < "$file" > "$tmpfile"
        mv "$tmpfile" "$queue/$name"
        i=$((i + 1))
    done
done

# vim:ts=4 sts=4 sw=4 et
