#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf 'Usage: %s -o <syncdir> <old-name> <new-name>\n' "${0##*/}" >&2
    exit 1
}

syncdir=
while getopts "o:" opt
do
    case "$opt" in
        o) syncdir="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND-1))
[ $# -eq 2 ] || usage
old_name="$1"
new_name="$2"
[ -n "$syncdir" ] || usage
cd "$syncdir/"
mv -Tv "$old_name" "$new_name"
for synced in */.synced/
do
    [ -e "$synced$old_name" ] && mv -Tv "$synced$old_name" "$synced$new_name"
done

# vim:ts=4 sts=4 sw=4 et
