#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

usage()
{
    printf '%s -o <syncdir> <testcase>...\n' "$0" >&2
    exit 1
}

syncdir=
while getopts "o:" opt
do
    case "$opt" in
        o) syncdir="$OPTARG";;
        *) exit 1;;
    esac
done
shift $((OPTIND-1))
[ $# -ne 0 ] || usage

ls -d "$syncdir/" > /dev/null
queue="$syncdir/inject/queue"
mkdir -p "$queue"
i=$(cd "$queue" && ls id:* | sed -e 's/id:0*\([0-9]\+\).*/\1/;' | sort -n | tail -n1)
i=$((i + 1))
for file in "$@"
do
    tmpfile=$(mktemp -p "$queue" .tmpinject.XXXXX)
    name=$(printf "id:%06d,inject" $i)
    printf '%s -> %s\n' "$file" "$queue/$name"
    cat < "$file" > "$tmpfile"
    mv "$tmpfile" "$queue/$name"
    i=$((i + 1))
done

# vim:ts=4 sts=4 sw=4 et
