#!/usr/bin/python3

# Copyright © 2015-2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import collections
import os
import resource
import shlex
import subprocess as ipc

def run_gdb(options, path):
    if '@@' in options.arguments:
        target_args = ' '.join(
            map(shlex.quote, (
                x if x != '@@' else path
                for x in options.arguments
            ))
        )
        gdb_run_command = 'run {args} >/dev/null 2>/dev/null'.format(
            args=target_args
        )
    else:
        target_args = ' '.join(
            map(shlex.quote, options.arguments)
        )
        gdb_run_command = 'run {args} < {path} >/dev/null 2>/dev/null'.format(
            args=target_args,
            path=shlex.quote(path)
        )
    gdb_cmdline = ['gdb', '--batch', '--quiet',
        '--ex', gdb_run_command,
        '--ex', 'backtrace',
        options.command
    ]
    gdb = ipc.Popen(gdb_cmdline, stdout=ipc.PIPE, stderr=ipc.PIPE)
    stdout, stderr = gdb.communicate()
    return (
        stdout.decode('ASCII', 'replace'),
        stderr.decode('ASCII', 'replace'),
    )

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-i', metavar='<input-file>', nargs='+', required=True)
    ap.add_argument('-m', type=int, default=100, metavar='<n>')
    ap.add_argument('command', metavar='<command>')
    ap.add_argument('arguments', nargs='*', metavar='<argument>')
    options = ap.parse_args()
    mem_limit = options.m << 20
    resource.setrlimit(resource.RLIMIT_AS, [mem_limit, mem_limit])
    if 'ASAN_OPTIONS' not in os.environ:
        os.environ['ASAN_OPTIONS'] = (
            'abort_on_error=1:'
            'detect_leaks=0:'
            'symbolize=0:'
            'allocator_may_return_null=1'
        )
    crashdata = collections.defaultdict(set)
    for path in options.i:
        [stdout, stderr] = run_gdb(options, path)
        crashdata[(stdout, stderr)].add(path)
    for (stdout, stderr), paths in sorted(crashdata.items()):
        for path in sorted(paths):
            print(path)
        for line in stdout.split('\n'):
            print('|', line)
        for line in stderr.split('\n'):
            print('#', line)
        print()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
